TELEMETRY_ENABLE=false

POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0password

REDIS_HOST=redis
REDIS_PORT=6379

RAILS_MAX_THREADS=8
RAILS_SERVER_PROCESSES=2

ENABLE_WAIT_RESULT=true
ENABLE_BATCHED_SUBMISSIONS=true
