export const LANGUAGES = [
  { id: 63, name: 'JavaScript (Node.js 12.14.0)', monacoLang: 'javascript', slug: 'javascript' },
  { id: 71, name: 'Python (3.8.1)', monacoLang: 'python', slug: 'python' },
  { id: 62, name: 'Java (OpenJDK 13.0.1)', monacoLang: 'java', slug: 'java' },
  { id: 54, name: 'C++ (GCC 9.2.0)', monacoLang: 'cpp', slug: 'cpp' },
  { id: 50, name: 'C (GCC 9.2.0)', monacoLang: 'c', slug: 'c' },
  { id: 72, name: 'Ruby (2.7.0)', monacoLang: 'ruby', slug: 'ruby' },
  { id: 60, name: 'Go (1.13.5)', monacoLang: 'go', slug: 'go' },
  { id: 73, name: 'Rust (1.40.0)', monacoLang: 'rust', slug: 'rust' },
  { id: 78, name: 'Kotlin (1.3.70)', monacoLang: 'kotlin', slug: 'kotlin' },
  { id: 74, name: 'TypeScript (3.7.4)', monacoLang: 'typescript', slug: 'typescript' },
  { id: 51, name: 'C# (Mono 6.6.0)', monacoLang: 'csharp', slug: 'csharp' },
];

export const JUDGE0_STATUS = {
  IN_QUEUE: 1,
  PROCESSING: 2,
  ACCEPTED: 3,
  WRONG_ANSWER: 4,
  TIME_LIMIT: 5,
  COMPILATION_ERROR: 6,
  RUNTIME_ERROR_SIGSEGV: 7,
  RUNTIME_ERROR_SIGXFSZ: 8,
  RUNTIME_ERROR_SIGFPE: 9,
  RUNTIME_ERROR_SIGABRT: 10,
  RUNTIME_ERROR_NZEC: 11,
  RUNTIME_ERROR_OTHER: 12,
  INTERNAL_ERROR: 13,
  EXEC_FORMAT_ERROR: 14,
};
